########### These MUST be filled in for a storm configuration
storm.zookeeper.servers:
     - "cloudera-master"


nimbus.host: "cloudera-master"
ui.port: 9090

storm.local.dir: "/mnt/storm"
# 
# 
# ##### These may optionally be filled in:
#    
## List of custom serializations
# topology.kryo.register:
#     - org.mycompany.MyType
#     - org.mycompany.MyType2: org.mycompany.MyType2Serializer
#
## List of custom kryo decorators
# topology.kryo.decorators:
#     - org.mycompany.MyDecorator
#
## Locations of the drpc servers
# drpc.servers:
#     - "server1"
#     - "server2"
